### ISSUE TITLE
Fix tooltip on bubble chart

### ISSUE THREAD

**Issue by fernandobrito** [fernandobrito/ufpb_sigaa_api#8]
We use course grade on two dimensions on the bubble chart (Y and color). Tooltip shows "Nota:" two times. We should override the default tooltip to hide one of the dimesions.

**Comment by gustavosobral** [comment]
Here [1] I found that the HTMLTooltip for the Bubble Chart is not allowed, but the 'regular' tooltip seems to work. But here [2] appears meaning that neither the regular works. Maybe this issue can not be solved.

[1] https://developers.google.com/chart/interactive/docs/gallery/bubblechart#configuration-options
[2] https://developers.google.com/chart/interactive/docs/roles#what-roles-are-available

**Comment by gustavosobral** [comment]
Closing due to PR #16
